#![forbid(unsafe_code)]
//! Cross-repo integration proof: a **real crebain-emitted capture** flows
//! through galadriel end to end.
//!
//! The fixture was generated by crebain's own emitter (its `#[ignore]`d
//! `generate_galadriel_pid_fixture` test: one constant-velocity target, three
//! modalities — visual/acoustic Cartesian, radar through the EKF polar path —
//! measurement noise matched to the declared R, 160 frames; regenerated at
//! crebain ada3eea after audit fix B6 changed mixed-modality birth-representative
//! selection), NOT hand-written:
//! every line is a `PidObservation` crebain's `update_track` actually produced
//! (`emit_innovations` + research fields). Regenerate with
//! `CREBAIN_PID_FIXTURE_PATH=… cargo test generate_galadriel_pid_fixture -- --ignored`
//! in crebain and copy the output here.
//!
//! What this proves beyond the byte-frozen golden contracts on both sides:
//! genuine emitter output *parses*, covers all expected modalities with
//! χ²(3)-plausible NIS. The baseline does not false-alarm, while the current
//! producer does not emit a common-frame/frozen-prior consistency projection, so
//! fusion must preserve a fail-closed result rather than comparing native residuals.

use galadriel_core::{
    assess_default, CorrConfig, DetectorConfig, FusedVerdict, Mirror, Modality, Verdict,
};
use galadriel_ncp::{read_jsonl, SidecarEnvelope};

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/crebain_clean_capture.jsonl"
);

#[test]
fn crebain_capture_parses_with_full_modality_coverage_and_sane_nis() {
    let stream = read_jsonl(FIXTURE).expect("crebain capture parses");
    assert!(stream.len() > 400, "rich capture, got {}", stream.len());

    for modality in [Modality::Visual, Modality::Radar, Modality::Acoustic] {
        let n = stream.iter().filter(|o| o.modality == modality).count();
        assert!(n > 150, "{modality:?}: {n} records");
    }
    assert!(stream.iter().all(|o| o.dof == 3));
    assert!(stream.iter().all(|o| o.nis.is_finite() && o.nis >= 0.0));
    // Native research fields are present, but no common consistency projection is.
    assert!(stream
        .iter()
        .all(|o| o.innovation.is_some() && o.innovation_cov.is_some()));
    assert!(
        stream.iter().all(|o| o.consistency_projection.is_none()),
        "legacy crebain capture must not be silently treated as common-frame data"
    );
    // Healthy-filter capture: mean NIS ≈ dof (χ²(3)); a gross model mismatch
    // between the repos would show up here first.
    let mean_nis = stream.iter().map(|o| o.nis).sum::<f64>() / stream.len() as f64;
    assert!(
        (mean_nis - 3.0).abs() < 0.6,
        "mean NIS {mean_nis:.2} should be ≈ dof for a matched filter"
    );
}

#[test]
fn crebain_clean_capture_keeps_insufficient_correlation_fail_closed() {
    let stream = read_jsonl(FIXTURE).expect("crebain capture parses");
    let modalities = [Modality::Visual, Modality::Radar, Modality::Acoustic];

    // The NIS χ² baseline.
    let mut mirror = Mirror::new(DetectorConfig::default()).expect("valid default config");
    for observation in &stream {
        mirror
            .ingest(observation)
            .expect("fixture remains valid and ordered");
    }
    let last = stream.iter().map(|o| o.seq).max().unwrap_or(0);
    let report = mirror
        .assess(1, last)
        .expect("baseline assessment succeeds");
    assert!(
        !matches!(
            report.verdict,
            Verdict::AttributedInconsistency { .. } | Verdict::BroadDegradation
        ),
        "clean crebain capture must not alarm the baseline: {:?}",
        report.verdict
    );

    // Native radar-polar and Cartesian innovations are intentionally ignored. The
    // producer supplied no common frame/context/frozen-prior attestation.
    let fused = assess_default(
        &stream,
        &modalities,
        &DetectorConfig::default(),
        &CorrConfig::default(),
    )
    .expect("fused assessment succeeds");
    assert!(fused.correlations.is_empty());
    assert_eq!(
        fused.verdict,
        FusedVerdict::InsufficientEvidence,
        "fusion must preserve insufficient correlation evidence"
    );
}

#[test]
fn current_crebain_record_roundtrips_inside_the_live_v1_envelope() {
    let stream = read_jsonl(FIXTURE).expect("crebain capture parses");
    let envelope = SidecarEnvelope::try_new(
        "crebain-capture-epoch-1",
        "crebain",
        stream.first().expect("fixture is nonempty").clone(),
    )
    .expect("current Crebain record satisfies the live envelope contract");
    let bytes = serde_json::to_vec(&envelope).expect("envelope serializes");
    let decoded: SidecarEnvelope =
        serde_json::from_slice(&bytes).expect("envelope deserializes identically");

    assert!(decoded
        .validate_for("crebain-capture-epoch-1", "crebain")
        .expect("version and provenance match")
        .is_match());
    assert!(decoded.observation.consistency_projection.is_none());
}
