#![forbid(unsafe_code)]
//! Cross-repo integration proof: a **real crebain-emitted capture** flows
//! through galadriel end to end.
//!
//! The fixture was generated by crebain's own emitter (its `#[ignore]`d
//! `generate_galadriel_pid_fixture` test: one constant-velocity target, three
//! modalities — visual/acoustic Cartesian, radar through the EKF polar path —
//! measurement noise matched to the declared R, 160 frames; regenerated at
//! crebain ada3eea after audit fix B6 changed mixed-modality birth-representative
//! selection), NOT hand-written:
//! every line is a `PidObservation` crebain's `update_track` actually produced
//! (`emit_innovations` + research fields). Regenerate with
//! `CREBAIN_PID_FIXTURE_PATH=… cargo test generate_galadriel_pid_fixture -- --ignored`
//! in crebain and copy the output here.
//!
//! What this proves beyond the byte-frozen golden contracts on both sides:
//! genuine emitter output *parses*, covers all expected modalities with
//! χ²(3)-plausible NIS. The baseline does not false-alarm, while the current
//! producer does not emit a common-frame/frozen-prior consistency projection, so
//! fusion must preserve a fail-closed result rather than comparing native residuals.
//!
//! The historical JSONL surface recorded successful applied updates, not explicit
//! misses. This authentic capture therefore has no acoustic record at fusion
//! sequence 98. The 0.9 release profile correctly treats the resulting acoustic
//! 97→99 jump as requiring a new generation; the baseline smoke test below uses
//! only the complete contiguous prefix through sequence 97.

use galadriel_core::{
    assess_default, FailureCode, FusedVerdict, Mirror, Modality, PidObservation, ReleaseSuite,
    Verdict,
};
use galadriel_ncp::{read_jsonl, SidecarEnvelope};

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/crebain_clean_capture.jsonl"
);
const FIRST_INCOMPLETE_SEQUENCE: u64 = 98;

fn complete_contiguous_prefix(stream: &[PidObservation]) -> &[PidObservation] {
    let prefix_end = stream
        .iter()
        .position(|observation| observation.sequence().get() == FIRST_INCOMPLETE_SEQUENCE)
        .expect("fixture contains the known incomplete frame");
    &stream[..prefix_end]
}

#[test]
fn crebain_capture_parses_with_full_modality_coverage_and_sane_nis() {
    let stream = read_jsonl(FIXTURE).expect("crebain capture parses");
    assert!(stream.len() > 400, "rich capture, got {}", stream.len());

    for modality in [Modality::Visual, Modality::Radar, Modality::Acoustic] {
        let n = stream
            .iter()
            .filter(|observation| observation.modality() == modality)
            .count();
        assert!(n > 150, "{modality:?}: {n} records");
    }
    assert!(stream.iter().all(|observation| observation.dof() == 3));
    assert!(stream
        .iter()
        .all(|observation| observation.nis().is_finite() && observation.nis() >= 0.0));
    // Native research fields are present, but no common consistency projection is.
    assert!(stream
        .iter()
        .all(|observation| observation.innovation().is_some()
            && observation.innovation_covariance().is_some()));
    assert!(
        stream
            .iter()
            .all(|observation| observation.consistency_projection().is_none()),
        "legacy crebain capture must not be silently treated as common-frame data"
    );
    // Healthy-filter capture: mean NIS ≈ dof (χ²(3)); a gross model mismatch
    // between the repos would show up here first.
    let mean_nis = stream
        .iter()
        .map(|observation| observation.nis())
        .sum::<f64>()
        / stream.len() as f64;
    assert!(
        (mean_nis - 3.0).abs() < 0.6,
        "mean NIS {mean_nis:.2} should be ≈ dof for a matched filter"
    );
}

#[test]
fn crebain_historical_capture_requires_reset_at_the_acoustic_omission() {
    let stream = read_jsonl(FIXTURE).expect("crebain capture parses");

    let incomplete_frame: Vec<_> = stream
        .iter()
        .filter(|observation| observation.sequence().get() == FIRST_INCOMPLETE_SEQUENCE)
        .map(|observation| observation.modality())
        .collect();
    assert_eq!(incomplete_frame.len(), 2);
    assert!(incomplete_frame.contains(&Modality::Visual));
    assert!(incomplete_frame.contains(&Modality::Radar));
    assert!(!incomplete_frame.contains(&Modality::Acoustic));

    let suite = ReleaseSuite::standalone_advisory_v0_9(&[
        Modality::Visual,
        Modality::Radar,
        Modality::Acoustic,
    ])
    .expect("valid release suite and modality contract");
    let mut mirror = Mirror::from_release_suite(&suite);
    let (observation, failure) = stream
        .iter()
        .find_map(|observation| {
            mirror
                .ingest_checked(observation)
                .err()
                .map(|failure| (observation, failure))
        })
        .expect("the historical omission requires a new generation");
    assert_eq!(
        (
            observation.sequence().get(),
            observation.modality(),
            failure.code(),
        ),
        (99, Modality::Acoustic, FailureCode::ResetRequired)
    );
}

#[test]
fn crebain_contiguous_prefix_keeps_insufficient_correlation_fail_closed() {
    let stream = read_jsonl(FIXTURE).expect("crebain capture parses");
    let continuous = complete_contiguous_prefix(&stream);
    let modalities = [Modality::Visual, Modality::Radar, Modality::Acoustic];

    // The NIS χ² baseline, over the complete pre-omission generation only.
    let suite = ReleaseSuite::standalone_advisory_v0_9(&modalities)
        .expect("valid release suite and modality contract");
    let mut mirror = Mirror::from_release_suite(&suite);
    for observation in continuous {
        mirror
            .ingest(observation)
            .expect("contiguous prefix remains valid and ordered");
    }
    let last = continuous
        .iter()
        .map(|observation| observation.sequence())
        .max()
        .expect("contiguous prefix contains observations");
    let track_id = continuous
        .first()
        .expect("contiguous prefix contains observations")
        .track_id();
    let report = mirror
        .assess(track_id, last)
        .expect("baseline assessment succeeds");
    assert!(
        !matches!(
            report.verdict(),
            Verdict::AttributedInconsistency { .. } | Verdict::BroadDegradation
        ),
        "clean crebain capture must not alarm the baseline: {:?}",
        report.verdict()
    );

    // Native radar-polar and Cartesian innovations are intentionally ignored. The
    // producer supplied no common frame/context/frozen-prior attestation.
    let fused = assess_default(continuous, &suite).expect("fused assessment succeeds");
    assert!(fused.correlations().is_empty());
    assert_eq!(
        fused.verdict(),
        &FusedVerdict::InsufficientEvidence,
        "fusion must preserve insufficient correlation evidence"
    );
}

#[test]
fn current_crebain_record_roundtrips_inside_the_live_v1_envelope() {
    let stream = read_jsonl(FIXTURE).expect("crebain capture parses");
    let envelope = SidecarEnvelope::try_new(
        "crebain-capture-epoch-1",
        "crebain",
        stream.first().expect("fixture is nonempty").clone(),
    )
    .expect("current Crebain record satisfies the live envelope contract");
    let bytes = serde_json::to_vec(&envelope).expect("envelope serializes");
    let decoded: SidecarEnvelope =
        serde_json::from_slice(&bytes).expect("envelope deserializes identically");

    assert!(decoded
        .validate_for("crebain-capture-epoch-1", "crebain")
        .expect("version and provenance match")
        .is_match());
    assert!(decoded.observation().consistency_projection().is_none());
}
