//! Cross-repo integration proof: a **real crebain-emitted capture** flows
//! through galadriel end to end.
//!
//! The fixture was generated by crebain's own emitter (its `#[ignore]`d
//! `generate_galadriel_pid_fixture` test: one constant-velocity target, three
//! modalities — visual/acoustic Cartesian, radar through the EKF polar path —
//! measurement noise matched to the declared R, 160 frames), NOT hand-written:
//! every line is a `PidObservation` crebain's `update_track` actually produced
//! (`emit_innovations` + research fields). Regenerate with
//! `CREBAIN_PID_FIXTURE_PATH=… cargo test generate_galadriel_pid_fixture -- --ignored`
//! in crebain and copy the output here.
//!
//! What this proves beyond the byte-frozen golden contracts on both sides:
//! genuine emitter output *parses*, covers all expected modalities with
//! χ²(3)-plausible NIS, and — the operational claim — a clean capture does
//! **not** false-alarm either the NIS baseline or the fused correlation
//! default.

use galadriel_core::{assess_default, CorrConfig, DetectorConfig, Mirror, Modality, Verdict};
use galadriel_ncp::read_jsonl;

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/crebain_clean_capture.jsonl"
);

#[test]
fn crebain_capture_parses_with_full_modality_coverage_and_sane_nis() {
    let stream = read_jsonl(FIXTURE).expect("crebain capture parses");
    assert!(stream.len() > 400, "rich capture, got {}", stream.len());

    for modality in [Modality::Visual, Modality::Radar, Modality::Acoustic] {
        let n = stream.iter().filter(|o| o.modality == modality).count();
        assert!(n > 150, "{modality:?}: {n} records");
    }
    assert!(stream.iter().all(|o| o.dof == 3));
    assert!(stream.iter().all(|o| o.nis.is_finite() && o.nis >= 0.0));
    // Research fields present (the PID/correlation engines key off them).
    assert!(stream
        .iter()
        .all(|o| o.innovation.is_some() && o.innovation_cov.is_some()));
    // Healthy-filter capture: mean NIS ≈ dof (χ²(3)); a gross model mismatch
    // between the repos would show up here first.
    let mean_nis = stream.iter().map(|o| o.nis).sum::<f64>() / stream.len() as f64;
    assert!(
        (mean_nis - 3.0).abs() < 0.6,
        "mean NIS {mean_nis:.2} should be ≈ dof for a matched filter"
    );
}

#[test]
fn crebain_clean_capture_does_not_false_alarm_the_detectors() {
    let stream = read_jsonl(FIXTURE).expect("crebain capture parses");
    let modalities = [Modality::Visual, Modality::Radar, Modality::Acoustic];

    // The NIS χ² baseline.
    let mut mirror = Mirror::new(DetectorConfig::default());
    for observation in &stream {
        mirror.ingest(observation);
    }
    let last = stream.iter().map(|o| o.seq).max().unwrap_or(0);
    let report = mirror.assess(1, last);
    assert!(
        !matches!(report.verdict, Verdict::Spoof { .. } | Verdict::Jam),
        "clean crebain capture must not alarm the baseline: {:?}",
        report.verdict
    );

    // The fused NIS ⊕ |ρ| correlation default (the shipped detector).
    let fused = assess_default(
        &stream,
        &modalities,
        &DetectorConfig::default(),
        &CorrConfig::default(),
    );
    assert!(
        !matches!(
            fused.verdict,
            galadriel_core::FusedVerdict::Spoof { .. } | galadriel_core::FusedVerdict::Jam
        ),
        "clean crebain capture must not alarm the fused default: {:?}",
        fused.verdict
    );
}
