"""Adversarial tests for shared qualification artifact validators."""

from __future__ import annotations

import copy
import gzip
import hashlib
import io
import json
import sys
import tarfile
import unittest
from dataclasses import replace
from pathlib import Path
from unittest import mock

TOOLS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(TOOLS))

from common import ReviewError  # noqa: E402
import qualification_artifacts as artifacts  # noqa: E402
from qualification_artifacts import (  # noqa: E402
    CARGO_DENY_HOST_FILTERED_SCOPE,
    EXPECTED_HOST_FILTERED_LICENSE_PACKAGES,
    EXPECTED_LICENSE_ACCEPTED_HELP_COUNT,
    EXPECTED_LICENSE_SKIPPED_NOTE_COUNT,
    CargoPackage,
    CargoTargetComponent,
    ValidatedCargoGraph,
    deterministic_cyclonedx_identity,
    validate_cargo_deny_license_inventory,
    validate_cargo_deny_license_policy_jsonl,
    validate_cargo_graph_paths,
    validate_cargo_metadata,
    validate_crate_archive,
    validate_cyclonedx_sbom,
)


VERSION = "0.9.0"
COMMIT = "a" * 40
SOURCE_DATE_EPOCH = 1_785_283_200
CHECKSUM = "b" * 64
WORKSPACE_ROOT = "/fixture/galadriel"
REGISTRY = "registry+https://github.com/rust-lang/crates.io-index"
GIT_BASE = f"git+https://github.com/example/NCP?rev={COMMIT}"
GIT_SOURCE = f"{GIT_BASE}#{COMMIT}"
WORKSPACE_NAMES = (
    "galadriel-cli",
    "galadriel-core",
    "galadriel-eval",
    "galadriel-justify",
    "galadriel-ncp",
    "galadriel-pid",
    "galadriel-sim",
)


def encode_json(value: object) -> bytes:
    return json.dumps(value, separators=(",", ":"), sort_keys=True).encode()


def package_id(
    name: str,
    version: str,
    source: str | None,
) -> str:
    if source is None:
        return f"path+file://{WORKSPACE_ROOT}/crates/{name}#{version}"
    if source.startswith("git+"):
        return f"{source.rsplit('#', 1)[0]}#{name}@{version}"
    return f"{source}#{name}@{version}"


def dependency_declaration(name: str, source: str) -> dict[str, object]:
    return {
        "name": name,
        "source": source,
        "req": "^1",
        "kind": None,
        "rename": None,
        "optional": False,
        "uses_default_features": True,
        "features": [],
        "target": None,
        "registry": None,
    }


def metadata_package(
    name: str,
    version: str,
    source: str | None,
    *,
    dependencies: list[dict[str, object]] | None = None,
) -> dict[str, object]:
    workspace = source is None
    manifest_path = (
        f"{WORKSPACE_ROOT}/crates/{name}/Cargo.toml"
        if workspace
        else f"/cargo/sources/{name}-{version}/Cargo.toml"
    )
    features: dict[str, list[str]] = {}
    if name == "galadriel-cli":
        features = {"default": [], "ncp": []}
    elif name == "galadriel-ncp":
        features = {"default": [], "zenoh": []}
    target_name = name.replace("-", "_")
    authors = ["Sepehr Mahmoudian"] if workspace else ["Fixture Author"]
    return {
        "name": name,
        "version": version,
        "id": package_id(name, version, source),
        "license": "MIT OR Apache-2.0",
        "license_file": None,
        "description": f"{name} fixture package.",
        "source": source,
        "dependencies": dependencies or [],
        "targets": [
            {
                "kind": ["lib"],
                "crate_types": ["lib"],
                "name": target_name,
                "src_path": manifest_path.removesuffix("Cargo.toml") + "src/lib.rs",
                "edition": "2021",
                "doc": True,
                "doctest": True,
                "test": True,
            }
        ],
        "features": features,
        "manifest_path": manifest_path,
        "metadata": None,
        "publish": [] if workspace else None,
        "authors": authors,
        "categories": [],
        "keywords": [],
        "readme": None,
        "repository": f"https://github.com/example/{name}",
        "homepage": f"https://example.invalid/{name}",
        "documentation": f"https://docs.example/{name}",
        "edition": "2021",
        "links": None,
        "default_run": None,
        "rust_version": None,
    }


def lockfile_bytes(packages: list[dict[str, object]]) -> bytes:
    lines = [
        "# This file is automatically @generated by Cargo.",
        "version = 4",
        "",
    ]
    for package in packages:
        lines.extend(
            [
                "[[package]]",
                f"name = {json.dumps(package['name'])}",
                f"version = {json.dumps(package['version'])}",
            ]
        )
        if package.get("source") is not None:
            lines.append(f"source = {json.dumps(package['source'])}")
        if package.get("checksum") is not None:
            lines.append(f"checksum = {json.dumps(package['checksum'])}")
        dependencies = package.get("dependencies", [])
        if dependencies:
            encoded = ", ".join(json.dumps(item) for item in dependencies)
            lines.append(f"dependencies = [{encoded}]")
        lines.append("")
    return "\n".join(lines).encode()


def metadata_fixture() -> tuple[dict[str, object], bytes]:
    serde_id = package_id("serde", "1.0.0", REGISTRY)
    ncp_id = package_id("ncp-core", "1.0.0", GIT_SOURCE)
    packages = [
        metadata_package(
            name,
            VERSION,
            None,
            dependencies=(
                [dependency_declaration("serde", REGISTRY)]
                if name == "galadriel-core"
                else [dependency_declaration("ncp-core", GIT_BASE)]
                if name == "galadriel-ncp"
                else []
            ),
        )
        for name in WORKSPACE_NAMES
    ]
    packages.extend(
        [
            metadata_package("serde", "1.0.0", REGISTRY),
            metadata_package("ncp-core", "1.0.0", GIT_SOURCE),
        ]
    )
    nodes: list[dict[str, object]] = []
    for package in packages:
        node_dependencies: list[str] = []
        dependency_rows: list[dict[str, object]] = []
        if package["name"] == "galadriel-core":
            node_dependencies = [serde_id]
            dependency_rows = [
                {
                    "name": "serde",
                    "pkg": serde_id,
                    "dep_kinds": [{"kind": None, "target": None}],
                }
            ]
        elif package["name"] == "galadriel-ncp":
            node_dependencies = [ncp_id]
            dependency_rows = [
                {
                    "name": "ncp_core",
                    "pkg": ncp_id,
                    "dep_kinds": [{"kind": None, "target": None}],
                }
            ]
        nodes.append(
            {
                "id": package["id"],
                "dependencies": node_dependencies,
                "deps": dependency_rows,
                "features": sorted(package["features"]),
            }
        )
    workspace_ids = [package_id(name, VERSION, None) for name in WORKSPACE_NAMES]
    document: dict[str, object] = {
        "packages": packages,
        "workspace_members": workspace_ids,
        "workspace_default_members": [
            package_id(name, VERSION, None)
            for name in (
                "galadriel-cli",
                "galadriel-core",
                "galadriel-sim",
            )
        ],
        "resolve": {"nodes": nodes, "root": None},
        "target_directory": "/fixture/target",
        "version": 1,
        "workspace_root": WORKSPACE_ROOT,
        "metadata": None,
    }
    lock_packages: list[dict[str, object]] = [
        {
            "name": name,
            "version": VERSION,
            "dependencies": (
                ["serde"]
                if name == "galadriel-core"
                else ["ncp-core"]
                if name == "galadriel-ncp"
                else []
            ),
        }
        for name in WORKSPACE_NAMES
    ]
    lock_packages.extend(
        [
            {
                "name": "serde",
                "version": "1.0.0",
                "source": REGISTRY,
                "checksum": CHECKSUM,
            },
            {
                "name": "ncp-core",
                "version": "1.0.0",
                "source": GIT_SOURCE,
            },
        ]
    )
    return document, lockfile_bytes(lock_packages)


def high_fanout_metadata_fixture(
    fanout: int,
) -> tuple[dict[str, object], bytes]:
    dependency_names = [f"fanout-package-{index:04d}" for index in range(fanout)]
    dependency_ids = [package_id(name, "1.0.0", REGISTRY) for name in dependency_names]
    packages = [
        metadata_package(
            name,
            VERSION,
            None,
            dependencies=(
                [
                    dependency_declaration(dependency_name, REGISTRY)
                    for dependency_name in dependency_names
                ]
                if name == "galadriel-core"
                else []
            ),
        )
        for name in WORKSPACE_NAMES
    ]
    packages.extend(
        metadata_package(name, "1.0.0", REGISTRY) for name in dependency_names
    )
    nodes: list[dict[str, object]] = []
    for package in packages:
        is_core = package["name"] == "galadriel-core"
        nodes.append(
            {
                "id": package["id"],
                "dependencies": dependency_ids if is_core else [],
                "deps": (
                    [
                        {
                            "name": name.replace("-", "_"),
                            "pkg": dependency_id,
                            "dep_kinds": [{"kind": None, "target": None}],
                        }
                        for name, dependency_id in zip(
                            dependency_names,
                            dependency_ids,
                            strict=True,
                        )
                    ]
                    if is_core
                    else []
                ),
                "features": sorted(package["features"]),
            }
        )
    workspace_ids = [package_id(name, VERSION, None) for name in WORKSPACE_NAMES]
    document: dict[str, object] = {
        "packages": packages,
        "workspace_members": workspace_ids,
        "workspace_default_members": [
            package_id(name, VERSION, None)
            for name in (
                "galadriel-cli",
                "galadriel-core",
                "galadriel-sim",
            )
        ],
        "resolve": {"nodes": nodes, "root": None},
        "target_directory": "/fixture/target",
        "version": 1,
        "workspace_root": WORKSPACE_ROOT,
        "metadata": None,
    }
    lock_packages: list[dict[str, object]] = [
        {
            "name": name,
            "version": VERSION,
            "dependencies": (dependency_names if name == "galadriel-core" else []),
        }
        for name in WORKSPACE_NAMES
    ]
    lock_packages.extend(
        {
            "name": name,
            "version": "1.0.0",
            "source": REGISTRY,
            "checksum": f"{index:064x}",
        }
        for index, name in enumerate(dependency_names)
    )
    return document, lockfile_bytes(lock_packages)


def validated_graph() -> ValidatedCargoGraph:
    metadata, lock = metadata_fixture()
    return validate_cargo_metadata(encode_json(metadata), lock)


ORIGINAL_CRATE_MANIFEST = (
    f'[package]\nname = "galadriel-core"\nversion = "{VERSION}"\npublish = false\n'
).encode()
GENERATED_CRATE_MANIFEST = (
    "# This file is generated by Cargo.\n"
    '[package]\nname = "galadriel-core"\n'
    f'version = "{VERSION}"\npublish = false\n'
).encode()
CRATE_SOURCE = b"#![forbid(unsafe_code)]\n"


def candidate_crate_files() -> dict[str, tuple[int, bytes]]:
    return {
        "Cargo.toml.orig": (0o644, ORIGINAL_CRATE_MANIFEST),
        "src/lib.rs": (0o644, CRATE_SOURCE),
    }


def crate_archive(
    *,
    duplicate_source: bool = False,
    extra_source: bool = False,
    include_lock: bool = False,
    omit_source: bool = False,
    substitute_source: bool = False,
    symbolic_source: bool = False,
    vcs_commit: str = COMMIT,
) -> bytes:
    prefix = f"galadriel-core-{VERSION}/"
    files = [
        ("Cargo.toml", GENERATED_CRATE_MANIFEST),
        ("Cargo.toml.orig", ORIGINAL_CRATE_MANIFEST),
        (
            ".cargo_vcs_info.json",
            encode_json(
                {
                    "git": {"sha1": vcs_commit},
                    "path_in_vcs": "crates/galadriel-core",
                }
            ),
        ),
    ]
    if not omit_source:
        files.append(
            (
                "src/lib.rs",
                b"substituted source\n" if substitute_source else CRATE_SOURCE,
            )
        )
    if duplicate_source:
        files.append(("src/lib.rs", b"duplicate\n"))
    if extra_source:
        files.append(("src/hidden.rs", b"pub fn hidden() {}\n"))
    if include_lock:
        files.append(("Cargo.lock", b"version = 4\n"))
    tar_payload = io.BytesIO()
    with tarfile.open(
        fileobj=tar_payload, mode="w", format=tarfile.USTAR_FORMAT
    ) as archive:
        for relative, content in files:
            member = tarfile.TarInfo(prefix + relative)
            member.uid = 0
            member.gid = 0
            member.mode = 0o644
            if symbolic_source and relative == "src/lib.rs":
                member.type = tarfile.SYMTYPE
                member.linkname = "../../outside"
                member.size = 0
                archive.addfile(member)
            else:
                member.size = len(content)
                archive.addfile(member, io.BytesIO(content))
    raw_tar = tar_payload.getvalue()
    payload_end = 0
    with tarfile.open(fileobj=io.BytesIO(raw_tar), mode="r:") as archive:
        for member in archive:
            payload_end = max(
                payload_end,
                member.offset_data + ((member.size + 511) // 512) * 512,
            )
    raw_tar = raw_tar[:payload_end] + bytes(1024)
    compressed = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=compressed, mtime=0) as stream:
        stream.write(raw_tar)
    return compressed.getvalue()


def sbom_fixture(graph: ValidatedCargoGraph) -> dict[str, object]:
    core = graph.package_by_name("galadriel-core")
    serde = graph.package_by_name("serde")
    core_purl = f"pkg:cargo/{core.name}@{core.version}?download_url=file://."
    identity = deterministic_cyclonedx_identity(
        candidate_commit=COMMIT,
        workspace_package=core.name,
        source_date_epoch=SOURCE_DATE_EPOCH,
    )
    return {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "serialNumber": identity.serial_number,
        "version": 1,
        "metadata": {
            "timestamp": identity.timestamp,
            "tools": [
                {
                    "vendor": "CycloneDX",
                    "name": "cargo-cyclonedx",
                    "version": "0.5.9",
                }
            ],
            "authors": [{"name": "Sepehr Mahmoudian"}],
            "properties": [
                {
                    "name": "cdx:rustc:sbom:target:all_targets",
                    "value": "true",
                }
            ],
            "component": {
                "type": "library",
                "bom-ref": core.package_id,
                "author": "Sepehr Mahmoudian",
                "name": core.name,
                "version": core.version,
                "description": core.description,
                "scope": "required",
                "licenses": [{"expression": "MIT OR Apache-2.0"}],
                "purl": core_purl,
                "externalReferences": [
                    {"type": "documentation", "url": core.documentation},
                    {"type": "website", "url": core.homepage},
                    {"type": "vcs", "url": core.repository},
                ],
                "components": [
                    {
                        "type": "library",
                        "bom-ref": f"{core.package_id} bin-target-0",
                        "name": "galadriel_core",
                        "version": core.version,
                        "purl": f"{core_purl}#src/lib.rs",
                    }
                ],
            },
        },
        "components": [
            {
                "type": "library",
                "bom-ref": serde.package_id,
                "author": "Fixture Author",
                "name": serde.name,
                "version": serde.version,
                "description": serde.description,
                "scope": "required",
                "hashes": [{"alg": "SHA-256", "content": CHECKSUM}],
                "licenses": [{"expression": "MIT OR Apache-2.0"}],
                "purl": f"pkg:cargo/{serde.name}@{serde.version}",
                "externalReferences": [
                    {"type": "documentation", "url": serde.documentation},
                    {"type": "website", "url": serde.homepage},
                    {"type": "vcs", "url": serde.repository},
                ],
            }
        ],
        "dependencies": [
            {"ref": core.package_id, "dependsOn": [serde.package_id]},
            {"ref": serde.package_id},
        ],
    }


def relocate_sbom_workspace_references(
    value: object,
    *,
    old_root: str,
    new_root: str,
) -> object:
    if isinstance(value, dict):
        return {
            key: relocate_sbom_workspace_references(
                item, old_root=old_root, new_root=new_root
            )
            for key, item in value.items()
        }
    if isinstance(value, list):
        return [
            relocate_sbom_workspace_references(
                item, old_root=old_root, new_root=new_root
            )
            for item in value
        ]
    if isinstance(value, str):
        return value.replace(
            f"path+file://{old_root}/crates/",
            f"path+file://{new_root}/crates/",
        )
    return value


def host_filtered_license_graph() -> ValidatedCargoGraph:
    base = validated_graph()
    packages = list(base.packages)
    filler_count = EXPECTED_HOST_FILTERED_LICENSE_PACKAGES - len(packages)
    for index in range(filler_count):
        name = f"fixture-package-{index:03d}"
        version = f"1.0.{index}"
        source = REGISTRY
        packages.append(
            CargoPackage(
                package_id=f"{source}#{name}@{version}",
                name=name,
                version=version,
                source=source,
                checksum=f"{index:064x}",
                manifest_path=f"/cargo/sources/{name}/Cargo.toml",
                workspace=False,
                authors=("Fixture Author",),
                description=f"{name} fixture package.",
                documentation=f"https://docs.example/{name}",
                homepage=f"https://example.invalid/{name}",
                repository=f"https://github.com/example/{name}",
                links=None,
                license="MIT",
                license_file=None,
                declared_features=(),
                resolved_features=(),
                dependencies=(),
                normal_dependencies=(),
                non_dev_dependencies=(),
                target_components=(
                    CargoTargetComponent(
                        name.replace("-", "_"),
                        "library",
                        f"/cargo/sources/{name}/src/lib.rs",
                    ),
                ),
            )
        )
    return ValidatedCargoGraph(
        workspace_root=base.workspace_root,
        target_directory=base.target_directory,
        packages=tuple(packages),
        workspace_package_ids=base.workspace_package_ids,
        default_workspace_package_ids=base.default_workspace_package_ids,
    )


def license_inventory(graph: ValidatedCargoGraph) -> dict[str, object]:
    result: dict[str, object] = {}
    for package in graph.packages:
        source = package.package_id.rsplit("#", 1)[0]
        result[f"{package.name} {package.version} {source}"] = {"licenses": ["MIT"]}
    return result


def license_inventory_expectations(
    graph: ValidatedCargoGraph,
    inventory: dict[str, object],
) -> tuple[int, str, str]:
    def semantic_package_id(package: CargoPackage) -> str:
        if package.workspace:
            return f"workspace+crates/{package.name}#{package.name}@{package.version}"
        return package.package_id

    packages = {
        (
            package.name,
            package.version,
            package.package_id.rsplit("#", 1)[0],
        ): package
        for package in graph.packages
    }
    rows: list[dict[str, object]] = []
    assignment_count = 0
    for identity, record_value in inventory.items():
        name, version, source = identity.split(" ", 2)
        package = packages[(name, version, source)]
        record = record_value
        if not isinstance(record, dict):
            raise AssertionError("test inventory record is not an object")
        licenses = record["licenses"]
        if not isinstance(licenses, list):
            raise AssertionError("test inventory licenses are not a list")
        assignment_count += len(licenses)
        rows.append(
            {
                "licenses": sorted(licenses),
                "package_id": semantic_package_id(package),
            }
        )
    rows.sort(key=lambda row: row["package_id"])
    package_ids = sorted(row["package_id"] for row in rows)

    def canonical(value: object) -> bytes:
        return json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode()

    return (
        assignment_count,
        hashlib.sha256(canonical(package_ids)).hexdigest(),
        hashlib.sha256(canonical(rows)).hexdigest(),
    )


def validate_synthetic_license_inventory(
    inventory: dict[str, object],
    graph: ValidatedCargoGraph,
    *,
    expected_inventory: dict[str, object] | None = None,
    expected_graph: ValidatedCargoGraph | None = None,
    scope: str = CARGO_DENY_HOST_FILTERED_SCOPE,
) -> artifacts.LicenseInventorySummary:
    expectation_inventory = (
        inventory if expected_inventory is None else expected_inventory
    )
    expectation_graph = graph if expected_graph is None else expected_graph
    assignments, package_ids_digest, semantic_digest = license_inventory_expectations(
        expectation_graph, expectation_inventory
    )
    with (
        mock.patch.object(
            artifacts,
            "EXPECTED_HOST_FILTERED_LICENSE_ASSIGNMENTS",
            assignments,
        ),
        mock.patch.object(
            artifacts,
            "EXPECTED_HOST_FILTERED_LICENSE_PACKAGE_IDS_SHA256",
            package_ids_digest,
        ),
        mock.patch.object(
            artifacts,
            "EXPECTED_HOST_FILTERED_LICENSE_SEMANTIC_SHA256",
            semantic_digest,
        ),
    ):
        return validate_cargo_deny_license_inventory(
            encode_json(inventory),
            graph,
            scope=scope,
        )


class JsonBoundsTest(unittest.TestCase):
    def test_rejects_deep_json_before_recursive_parsing(self) -> None:
        depth = artifacts.MAX_JSON_DEPTH + 1
        payload = b"[" * depth + b"0" + b"]" * depth
        with (
            mock.patch.object(
                artifacts.json,
                "loads",
                side_effect=AssertionError("parser must not run"),
            ),
            self.assertRaisesRegex(ReviewError, "JSON depth bound"),
        ):
            artifacts._load_json_bytes(
                payload,
                len(payload),
                "deep JSON fixture",
            )

    def test_rejects_excess_json_nodes_before_parsing(self) -> None:
        payload = b"[" + b",".join([b"0"] * 8) + b"]"
        with (
            mock.patch.object(artifacts, "MAX_JSON_NODES", 8),
            mock.patch.object(
                artifacts.json,
                "loads",
                side_effect=AssertionError("parser must not run"),
            ),
            self.assertRaisesRegex(ReviewError, "JSON node bound"),
        ):
            artifacts._load_json_bytes(
                payload,
                len(payload),
                "wide JSON fixture",
            )

    def test_bounds_parser_error_text_and_catches_recursion(self) -> None:
        detail = "sensitive-parser-detail-" * 1_000
        context = "large-context-" * 1_000
        with (
            mock.patch.object(
                artifacts.json,
                "loads",
                side_effect=RecursionError(detail),
            ),
            self.assertRaises(ReviewError) as caught,
        ):
            artifacts._load_json_bytes(b"{}", 2, context)
        message = str(caught.exception)
        self.assertNotIn(detail, message)
        self.assertLessEqual(
            len(message),
            artifacts.MAX_JSON_CONTEXT_CHARS + artifacts.MAX_JSON_ERROR_CHARS + 32,
        )

    def test_ignores_json_structure_inside_strings(self) -> None:
        payload = b'{"value":"[{\\"nested\\":true}]"}'
        self.assertEqual(
            artifacts._load_json_bytes(payload, len(payload), "string fixture"),
            {"value": '[{"nested":true}]'},
        )

    def test_omits_a_duplicate_key_from_the_error(self) -> None:
        duplicate_key = "private-key-material-" * 1_000
        payload = (
            "{" + json.dumps(duplicate_key) + ":0," + json.dumps(duplicate_key) + ":1}"
        ).encode()
        with self.assertRaisesRegex(ReviewError, "duplicate JSON key") as caught:
            artifacts._load_json_bytes(payload, len(payload), "duplicate fixture")
        self.assertNotIn(duplicate_key, str(caught.exception))


class CargoMetadataValidatorTest(unittest.TestCase):
    def test_binds_workspace_and_target_paths_to_the_candidate(self) -> None:
        graph = validated_graph()
        validate_cargo_graph_paths(
            graph,
            workspace_root=WORKSPACE_ROOT,
            target_directory="/fixture/target",
        )
        with self.assertRaisesRegex(ReviewError, "another qualification workspace"):
            validate_cargo_graph_paths(
                graph,
                workspace_root="/another/workspace",
                target_directory="/fixture/target",
            )
        with self.assertRaisesRegex(
            ReviewError,
            "another qualification target directory",
        ):
            validate_cargo_graph_paths(
                graph,
                workspace_root=WORKSPACE_ROOT,
                target_directory="/another/target",
            )

    def test_accepts_exact_workspace_and_locked_graph(self) -> None:
        graph = validated_graph()
        self.assertEqual(len(graph.packages), 9)
        self.assertEqual(
            {graph.package_by_id()[item].name for item in graph.workspace_package_ids},
            set(WORKSPACE_NAMES),
        )
        self.assertEqual(
            graph.package_by_name("serde").checksum,
            CHECKSUM,
        )

    def test_accepts_an_unrenamed_library_target_name(self) -> None:
        metadata, lock = metadata_fixture()
        serde_id = package_id("serde", "1.0.0", REGISTRY)
        serde = next(
            item
            for item in metadata["packages"]  # type: ignore[index]
            if item["id"] == serde_id
        )
        serde["targets"][0]["name"] = "serialization"  # type: ignore[index]
        core_id = package_id("galadriel-core", VERSION, None)
        core_node = next(
            item
            for item in metadata["resolve"]["nodes"]  # type: ignore[index]
            if item["id"] == core_id
        )
        core_node["deps"][0]["name"] = "serialization"  # type: ignore[index]
        graph = validate_cargo_metadata(encode_json(metadata), lock)
        self.assertEqual(graph.package_by_name("serde").name, "serde")

    def test_accepts_a_renamed_dependency(self) -> None:
        metadata, lock = metadata_fixture()
        core_id = package_id("galadriel-core", VERSION, None)
        core = next(
            item
            for item in metadata["packages"]  # type: ignore[index]
            if item["id"] == core_id
        )
        core["dependencies"][0]["rename"] = "serde-alias"  # type: ignore[index]
        core_node = next(
            item
            for item in metadata["resolve"]["nodes"]  # type: ignore[index]
            if item["id"] == core_id
        )
        core_node["deps"][0]["name"] = "serde_alias"  # type: ignore[index]
        graph = validate_cargo_metadata(encode_json(metadata), lock)
        self.assertEqual(
            graph.package_by_name("galadriel-core").dependencies,
            (package_id("serde", "1.0.0", REGISTRY),),
        )

    def test_rejects_lock_graph_drift(self) -> None:
        metadata, lock = metadata_fixture()
        core_id = package_id("galadriel-core", VERSION, None)
        node = next(
            item
            for item in metadata["resolve"]["nodes"]  # type: ignore[index]
            if item["id"] == core_id
        )
        node["dependencies"] = []
        node["deps"] = []
        with self.assertRaisesRegex(ReviewError, "declaration|Cargo.lock"):
            validate_cargo_metadata(encode_json(metadata), lock)

    def test_rejects_incomplete_all_feature_record(self) -> None:
        metadata, lock = metadata_fixture()
        cli_id = package_id("galadriel-cli", VERSION, None)
        node = next(
            item
            for item in metadata["resolve"]["nodes"]  # type: ignore[index]
            if item["id"] == cli_id
        )
        node["features"] = ["default"]
        with self.assertRaisesRegex(ReviewError, "all workspace features"):
            validate_cargo_metadata(encode_json(metadata), lock)

    def test_rejects_mutable_git_lock_source(self) -> None:
        metadata, lock = metadata_fixture()
        mutable = lock.replace(
            f"?rev={COMMIT}#{COMMIT}".encode(),
            b"?branch=main#" + COMMIT.encode(),
        )
        with self.assertRaisesRegex(ReviewError, "exact credential-free revision"):
            validate_cargo_metadata(encode_json(metadata), mutable)

    def test_accepts_high_fanout_with_indexed_dependency_matching(self) -> None:
        fanout = 512
        metadata, lock = high_fanout_metadata_fixture(fanout)
        with (
            mock.patch.object(
                artifacts,
                "_metadata_dependency_name_matches",
                wraps=artifacts._metadata_dependency_name_matches,
            ) as legacy_name_matcher,
            mock.patch.object(
                artifacts,
                "_resolve_lock_dependency",
                wraps=artifacts._resolve_lock_dependency,
            ) as lock_resolver,
        ):
            graph = validate_cargo_metadata(encode_json(metadata), lock)
        core = graph.package_by_name("galadriel-core")
        self.assertEqual(len(core.dependencies), fanout)
        self.assertLessEqual(legacy_name_matcher.call_count, fanout * 4)
        self.assertEqual(lock_resolver.call_count, fanout)
        self.assertTrue(
            all(
                isinstance(call.args[1], artifacts._LockDependencyIndex)
                for call in lock_resolver.call_args_list
            )
        )


class CrateArchiveValidatorTest(unittest.TestCase):
    def test_accepts_exact_unpublished_package(self) -> None:
        summary = validate_crate_archive(
            crate_archive(),
            crate_name="galadriel-core",
            version=VERSION,
            candidate_commit=COMMIT,
            candidate_files=candidate_crate_files(),
        )
        self.assertEqual(summary.member_count, 4)

    def test_rejects_duplicate_member(self) -> None:
        with self.assertRaisesRegex(ReviewError, "repeats a member path"):
            validate_crate_archive(
                crate_archive(duplicate_source=True),
                crate_name="galadriel-core",
                version=VERSION,
                candidate_commit=COMMIT,
                candidate_files=candidate_crate_files(),
            )

    def test_rejects_link_and_lockfile(self) -> None:
        with self.assertRaisesRegex(ReviewError, "unsafe type"):
            validate_crate_archive(
                crate_archive(symbolic_source=True),
                crate_name="galadriel-core",
                version=VERSION,
                candidate_commit=COMMIT,
                candidate_files=candidate_crate_files(),
            )
        with self.assertRaisesRegex(ReviewError, "contains Cargo.lock"):
            validate_crate_archive(
                crate_archive(include_lock=True),
                crate_name="galadriel-core",
                version=VERSION,
                candidate_commit=COMMIT,
                candidate_files=candidate_crate_files(),
            )

    def test_rejects_another_candidate(self) -> None:
        with self.assertRaisesRegex(ReviewError, "VCS identity"):
            validate_crate_archive(
                crate_archive(vcs_commit="c" * 40),
                crate_name="galadriel-core",
                version=VERSION,
                candidate_commit=COMMIT,
                candidate_files=candidate_crate_files(),
            )

    def test_rejects_omitted_substituted_and_extra_candidate_members(self) -> None:
        for archive_bytes in (
            crate_archive(omit_source=True),
            crate_archive(substitute_source=True),
            crate_archive(extra_source=True),
        ):
            with self.subTest(archive_size=len(archive_bytes)):
                with self.assertRaisesRegex(
                    ReviewError,
                    "member set differs|differs from the candidate",
                ):
                    validate_crate_archive(
                        archive_bytes,
                        crate_name="galadriel-core",
                        version=VERSION,
                        candidate_commit=COMMIT,
                        candidate_files=candidate_crate_files(),
                    )

    def test_rejects_candidate_map_without_original_manifest(self) -> None:
        candidate_files = candidate_crate_files()
        del candidate_files["Cargo.toml.orig"]
        with self.assertRaisesRegex(ReviewError, "omits Cargo.toml.orig"):
            validate_crate_archive(
                crate_archive(),
                crate_name="galadriel-core",
                version=VERSION,
                candidate_commit=COMMIT,
                candidate_files=candidate_files,
            )


class CycloneDxValidatorTest(unittest.TestCase):
    def test_accepts_exact_root_component_and_graph(self) -> None:
        graph = validated_graph()
        summary = validate_cyclonedx_sbom(
            encode_json(sbom_fixture(graph)),
            graph,
            workspace_package="galadriel-core",
            candidate_commit=COMMIT,
            source_date_epoch=SOURCE_DATE_EPOCH,
        )
        self.assertEqual(summary.component_count, 1)
        self.assertEqual(summary.dependency_record_count, 2)

    def test_accepts_consistently_relocated_workspace_references(self) -> None:
        graph = validated_graph()
        document = relocate_sbom_workspace_references(
            sbom_fixture(graph),
            old_root=WORKSPACE_ROOT,
            new_root="/private/qualification/sbom-worktree",
        )
        summary = validate_cyclonedx_sbom(
            encode_json(document),
            graph,
            workspace_package="galadriel-core",
            candidate_commit=COMMIT,
            source_date_epoch=SOURCE_DATE_EPOCH,
        )
        self.assertEqual(summary.workspace_package, "galadriel-core")

    def test_rejects_inconsistent_relocated_workspace_references(self) -> None:
        graph = validated_graph()
        document = relocate_sbom_workspace_references(
            sbom_fixture(graph),
            old_root=WORKSPACE_ROOT,
            new_root="/private/qualification/sbom-worktree",
        )
        component = document["metadata"]["component"]  # type: ignore[index]
        component["components"][0]["bom-ref"] = (  # type: ignore[index]
            f"{graph.package_by_name('galadriel-core').package_id} bin-target-0"
        )
        with self.assertRaisesRegex(ReviewError, "target identity"):
            validate_cyclonedx_sbom(
                encode_json(document),
                graph,
                workspace_package="galadriel-core",
                candidate_commit=COMMIT,
                source_date_epoch=SOURCE_DATE_EPOCH,
            )

    def test_rejects_registry_checksum_drift(self) -> None:
        graph = validated_graph()
        document = sbom_fixture(graph)
        document["components"][0]["hashes"][0]["content"] = "c" * 64  # type: ignore[index]
        with self.assertRaisesRegex(ReviewError, "identity differs"):
            validate_cyclonedx_sbom(
                encode_json(document),
                graph,
                workspace_package="galadriel-core",
                candidate_commit=COMMIT,
                source_date_epoch=SOURCE_DATE_EPOCH,
            )

    def test_rejects_null_metadata_author(self) -> None:
        graph = validated_graph()
        document = sbom_fixture(graph)
        document["metadata"]["authors"] = [None]  # type: ignore[index]
        with self.assertRaisesRegex(ReviewError, "authors differ"):
            validate_cyclonedx_sbom(
                encode_json(document),
                graph,
                workspace_package="galadriel-core",
                candidate_commit=COMMIT,
                source_date_epoch=SOURCE_DATE_EPOCH,
            )

    def test_rejects_unbound_serial_number_and_timestamp(self) -> None:
        graph = validated_graph()
        baseline = sbom_fixture(graph)
        mutations = (
            ("serialNumber", "urn:uuid:12345678-1234-4234-8234-123456789abc"),
            ("metadata.timestamp", "1970-01-01T00:00:00Z"),
        )
        for field, value in mutations:
            with self.subTest(field=field):
                document = copy.deepcopy(baseline)
                if field == "serialNumber":
                    document[field] = value
                else:
                    document["metadata"]["timestamp"] = value  # type: ignore[index]
                with self.assertRaisesRegex(
                    ReviewError,
                    "differs from the candidate|differs from the source-date epoch",
                ):
                    validate_cyclonedx_sbom(
                        encode_json(document),
                        graph,
                        workspace_package="galadriel-core",
                        candidate_commit=COMMIT,
                        source_date_epoch=SOURCE_DATE_EPOCH,
                    )

    def test_rejects_hidden_nested_component(self) -> None:
        graph = validated_graph()
        document = sbom_fixture(graph)
        document["components"][0]["components"] = [  # type: ignore[index]
            {
                "type": "library",
                "bom-ref": "hidden",
                "name": "hidden",
                "version": "1.0.0",
            }
        ]
        with self.assertRaisesRegex(ReviewError, "identity differs"):
            validate_cyclonedx_sbom(
                encode_json(document),
                graph,
                workspace_package="galadriel-core",
                candidate_commit=COMMIT,
                source_date_epoch=SOURCE_DATE_EPOCH,
            )

    def test_rejects_conflicting_component_identity_fields(self) -> None:
        graph = validated_graph()
        baseline = sbom_fixture(graph)
        mutations = {
            "purl": "pkg:cargo/other@1.0.0",
            "licenses": [{"expression": "Apache-2.0"}],
            "externalReferences": [
                {"type": "vcs", "url": "https://example.invalid/other"}
            ],
        }
        for field, value in mutations.items():
            with self.subTest(field=field):
                document = copy.deepcopy(baseline)
                document["components"][0][field] = value  # type: ignore[index]
                with self.assertRaisesRegex(ReviewError, "identity differs"):
                    validate_cyclonedx_sbom(
                        encode_json(document),
                        graph,
                        workspace_package="galadriel-core",
                        candidate_commit=COMMIT,
                        source_date_epoch=SOURCE_DATE_EPOCH,
                    )

    def test_rejects_incomplete_dependency_graph(self) -> None:
        graph = validated_graph()
        document = sbom_fixture(graph)
        document["dependencies"] = document["dependencies"][:1]  # type: ignore[index]
        with self.assertRaisesRegex(ReviewError, "incomplete"):
            validate_cyclonedx_sbom(
                encode_json(document),
                graph,
                workspace_package="galadriel-core",
                candidate_commit=COMMIT,
                source_date_epoch=SOURCE_DATE_EPOCH,
            )


class CargoDenyLicenseValidatorTest(unittest.TestCase):
    def test_accepts_exact_policy_summary(self) -> None:
        report = encode_json(
            {
                "type": "summary",
                "fields": {
                    "licenses": {
                        "errors": 0,
                        "helps": EXPECTED_LICENSE_ACCEPTED_HELP_COUNT,
                        "notes": EXPECTED_LICENSE_SKIPPED_NOTE_COUNT,
                        "warnings": 0,
                    }
                },
            }
        )
        summary = validate_cargo_deny_license_policy_jsonl(report)
        self.assertEqual(
            summary.accepted_help_count,
            EXPECTED_LICENSE_ACCEPTED_HELP_COUNT,
        )

    def test_rejects_policy_warning(self) -> None:
        report = encode_json(
            {
                "type": "summary",
                "fields": {
                    "licenses": {
                        "errors": 0,
                        "helps": EXPECTED_LICENSE_ACCEPTED_HELP_COUNT,
                        "notes": EXPECTED_LICENSE_SKIPPED_NOTE_COUNT,
                        "warnings": 1,
                    }
                },
            }
        )
        with self.assertRaisesRegex(ReviewError, "not exact and passing"):
            validate_cargo_deny_license_policy_jsonl(report)

    def test_accepts_explicit_host_filtered_inventory(self) -> None:
        graph = host_filtered_license_graph()
        summary = validate_synthetic_license_inventory(
            license_inventory(graph),
            graph,
        )
        self.assertEqual(
            summary.package_count,
            EXPECTED_HOST_FILTERED_LICENSE_PACKAGES,
        )
        self.assertEqual(summary.scope, CARGO_DENY_HOST_FILTERED_SCOPE)

    def test_rejects_empty_license_evidence_and_wrong_scope(self) -> None:
        graph = host_filtered_license_graph()
        expected_inventory = license_inventory(graph)
        inventory = copy.deepcopy(expected_inventory)
        first = next(iter(inventory))
        inventory[first] = {"licenses": []}
        with self.assertRaisesRegex(ReviewError, "no evidence"):
            validate_synthetic_license_inventory(
                inventory,
                graph,
                expected_inventory=expected_inventory,
            )
        with self.assertRaisesRegex(ReviewError, "another scope"):
            validate_synthetic_license_inventory(
                expected_inventory,
                graph,
                scope="TARGET_ALL",
            )

    def test_rejects_unknown_inventory_identity(self) -> None:
        graph = host_filtered_license_graph()
        inventory = license_inventory(graph)
        first = next(iter(inventory))
        value = inventory.pop(first)
        inventory["unknown 1.0.0 registry+https://example.invalid/index"] = value
        with self.assertRaisesRegex(ReviewError, "unknown package identity"):
            validate_synthetic_license_inventory(
                inventory,
                graph,
                expected_inventory=license_inventory(graph),
            )

    def test_rejects_arbitrary_license_substitution(self) -> None:
        graph = host_filtered_license_graph()
        expected_inventory = license_inventory(graph)
        inventory = copy.deepcopy(expected_inventory)
        first = next(iter(inventory))
        inventory[first] = {"licenses": ["Arbitrary-License"]}
        with self.assertRaisesRegex(ReviewError, "semantics are not exact"):
            validate_synthetic_license_inventory(
                inventory,
                graph,
                expected_inventory=expected_inventory,
            )

    def test_rejects_package_set_substitution(self) -> None:
        expected_graph = host_filtered_license_graph()
        expected_inventory = license_inventory(expected_graph)
        packages = list(expected_graph.packages)
        replaced_package = packages[-1]
        replacement_name = "substituted-package"
        packages[-1] = replace(
            replaced_package,
            package_id=f"{REGISTRY}#{replacement_name}@{replaced_package.version}",
            name=replacement_name,
            manifest_path=f"/cargo/sources/{replacement_name}/Cargo.toml",
        )
        graph = replace(expected_graph, packages=tuple(packages))
        inventory = license_inventory(graph)
        with self.assertRaisesRegex(ReviewError, "package set is not exact"):
            validate_synthetic_license_inventory(
                inventory,
                graph,
                expected_inventory=expected_inventory,
                expected_graph=expected_graph,
            )


if __name__ == "__main__":
    unittest.main()
