#!/usr/bin/env python3
"""Reject drift from the retained 0.9 Rust public-API snapshots.

The snapshots are generated by the pinned ``cargo-public-api`` tool and an
exact dated nightly rustdoc toolchain.  This verifier intentionally compares the
complete byte stream: filtering blanket implementations or normalizing changed
output would make a toolchain or surface change invisible to qualification.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

from common import ReviewError, safe_git_environment
from release_assurance import (
    run_bounded_host_command,
    sanitized_host_environment,
)


EXPECTED_TOOL_VERSION = "cargo-public-api 0.52.0"
PUBLIC_API_TOOLCHAIN = "nightly-2026-06-16"
EXPECTED_RUSTDOC_COMMIT = "01dfd79246f1b2d5f146616deff08223a840a9ae"
PUBLIC_API_COMMAND = ("cargo", f"+{PUBLIC_API_TOOLCHAIN}", "public-api")
MAX_DIFF_LINES = 200
BASELINE_SNAPSHOT = "release/0.9.0/api/galadriel-core.baseline.txt"
ACCEPTED_SNAPSHOT = "release/0.9.0/api/galadriel-core.0.9.0.txt"
RETAINED_DIFF = "release/0.9.0/evidence/galadriel-core-api.diff"
PUBLIC_API_TIMEOUT_SECONDS = 600
MAX_PUBLIC_API_STDOUT_BYTES = 16 * 1024 * 1024
MAX_PUBLIC_API_STDERR_BYTES = 1024 * 1024
MAX_PUBLIC_API_DIAGNOSTIC_CHARACTERS = 4 * 1024


@dataclass(frozen=True)
class ApiProfile:
    """One manifest and its exact retained API snapshot."""

    name: str
    manifest: str
    snapshot: str


PROFILES = (
    ApiProfile(
        "galadriel-core",
        "crates/galadriel-core/Cargo.toml",
        "release/0.9.0/api/galadriel-core.0.9.0.txt",
    ),
    ApiProfile(
        "galadriel-pid",
        "crates/galadriel-pid/Cargo.toml",
        "release/0.9.0/api/galadriel-pid.0.9.0.txt",
    ),
)


def digest(data: bytes) -> str:
    """Return a lowercase SHA-256 identity for diagnostic output."""

    return hashlib.sha256(data).hexdigest()


def compare_snapshot(name: str, expected: bytes, actual: bytes) -> None:
    """Raise with a bounded textual diff when an API stream changes."""

    if expected == actual:
        return
    expected_text = expected.decode("utf-8", "replace").splitlines()
    actual_text = actual.decode("utf-8", "replace").splitlines()
    diff = list(
        difflib.unified_diff(
            expected_text,
            actual_text,
            fromfile=f"{name}.retained",
            tofile=f"{name}.actual",
            n=3,
        )
    )
    excerpt = "\n".join(diff[:MAX_DIFF_LINES])
    if len(diff) > MAX_DIFF_LINES:
        excerpt += f"\n... {len(diff) - MAX_DIFF_LINES} additional diff lines omitted"
    raise ReviewError(
        f"{name}: public API snapshot drifted "
        f"(expected sha256={digest(expected)} bytes={len(expected)}, "
        f"actual sha256={digest(actual)} bytes={len(actual)})\n{excerpt}"
    )


def canonical_core_diff(repo: Path) -> bytes:
    """Render the baseline-to-0.9 API diff without filesystem timestamps."""

    baseline = (repo / BASELINE_SNAPSHOT).read_text(encoding="utf-8").splitlines()
    accepted = (repo / ACCEPTED_SNAPSHOT).read_text(encoding="utf-8").splitlines()
    lines = difflib.unified_diff(
        baseline,
        accepted,
        fromfile=BASELINE_SNAPSHOT,
        tofile=ACCEPTED_SNAPSHOT,
        n=3,
        lineterm="",
    )
    return ("\n".join(lines) + "\n").encode("utf-8")


def release_tool_environment(
    source: Mapping[str, str] | None = None,
) -> dict[str, str]:
    """Return host tool state without ambient credentials or network proxies."""

    environment = sanitized_host_environment(os.environ if source is None else source)
    environment = safe_git_environment(environment)
    environment["CARGO_TERM_COLOR"] = "never"
    return environment


def bounded_diagnostic(document: bytes) -> str:
    """Return one bounded UTF-8 diagnostic without command arguments."""

    text = document.decode("utf-8", "replace").strip()
    if len(text) <= MAX_PUBLIC_API_DIAGNOSTIC_CHARACTERS:
        return text
    omitted = len(text) - MAX_PUBLIC_API_DIAGNOSTIC_CHARACTERS
    return (
        text[:MAX_PUBLIC_API_DIAGNOSTIC_CHARACTERS]
        + f"\n... {omitted} additional characters omitted"
    )


def capture(argv: list[str], *, repo: Path) -> bytes:
    """Run one shell-free API command with deterministic terminal settings."""

    process = run_bounded_host_command(
        argv,
        cwd=repo,
        environment=release_tool_environment(),
        context="public API command",
        max_stdout_bytes=MAX_PUBLIC_API_STDOUT_BYTES,
        max_stderr_bytes=MAX_PUBLIC_API_STDERR_BYTES,
        timeout_seconds=PUBLIC_API_TIMEOUT_SECONDS,
    )
    if process.returncode != 0:
        raise ReviewError(
            "public API command failed with "
            f"{process.returncode}; stderr sha256={digest(process.stderr)} "
            f"bytes={len(process.stderr)}"
        )
    return process.stdout


def verify(repo: Path) -> None:
    """Verify tool identity and both retained API snapshots."""

    rustdoc_identity = capture(
        ["rustc", f"+{PUBLIC_API_TOOLCHAIN}", "--version", "--verbose"], repo=repo
    ).decode("utf-8", "strict")
    rustdoc_fields = dict(
        line.split(": ", 1) for line in rustdoc_identity.splitlines() if ": " in line
    )
    if rustdoc_fields.get("commit-hash") != EXPECTED_RUSTDOC_COMMIT:
        raise ReviewError(
            f"public-API rustdoc identity changed: expected commit "
            f"{EXPECTED_RUSTDOC_COMMIT}, got {rustdoc_fields.get('commit-hash')!r}"
        )
    version = (
        capture([*PUBLIC_API_COMMAND, "--version"], repo=repo)
        .decode("utf-8", "strict")
        .strip()
    )
    if version != EXPECTED_TOOL_VERSION:
        raise ReviewError(
            f"cargo-public-api identity changed: expected {EXPECTED_TOOL_VERSION!r}, "
            f"got {version!r}"
        )
    for profile in PROFILES:
        manifest = repo / profile.manifest
        snapshot = repo / profile.snapshot
        if not manifest.is_file() or not snapshot.is_file():
            raise ReviewError(
                f"{profile.name}: missing manifest or snapshot "
                f"({profile.manifest}, {profile.snapshot})"
            )
        actual = capture(
            [*PUBLIC_API_COMMAND, "--manifest-path", profile.manifest], repo=repo
        )
        compare_snapshot(profile.name, snapshot.read_bytes(), actual)
    retained_diff = repo / RETAINED_DIFF
    if not retained_diff.is_file():
        raise ReviewError(f"missing retained API diff: {RETAINED_DIFF}")
    compare_snapshot(
        "galadriel-core-api-diff",
        canonical_core_diff(repo),
        retained_diff.read_bytes(),
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=".")
    parser.add_argument(
        "--refresh-diff",
        action="store_true",
        help="rewrite only the deterministic baseline-to-0.9 diff after API verification",
    )
    arguments = parser.parse_args()
    try:
        repo = Path(arguments.repo).resolve()
        if arguments.refresh_diff:
            # Verify both source-derived snapshots before rewriting the derived
            # comparison artifact. Snapshots themselves are never rewritten by
            # this command.
            version = (
                capture([*PUBLIC_API_COMMAND, "--version"], repo=repo)
                .decode("utf-8", "strict")
                .strip()
            )
            if version != EXPECTED_TOOL_VERSION:
                raise ReviewError(
                    f"cargo-public-api identity changed: expected {EXPECTED_TOOL_VERSION!r}, "
                    f"got {version!r}"
                )
            for profile in PROFILES:
                actual = capture(
                    [*PUBLIC_API_COMMAND, "--manifest-path", profile.manifest],
                    repo=repo,
                )
                compare_snapshot(
                    profile.name, (repo / profile.snapshot).read_bytes(), actual
                )
            (repo / RETAINED_DIFF).write_bytes(canonical_core_diff(repo))
        verify(repo)
    except (OSError, UnicodeError, ReviewError) as error:
        print(f"public API verification failed: {error}", file=sys.stderr)
        return 2
    print("public API snapshots verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
